# Generated by Django 5.2.2 on 2025-06-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_add_disease_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Văn bản'), ('quick_reply', 'Trả lời nhanh'), ('card', 'Card'), ('appointment_booking', 'Đặt lịch hẹn'), ('doctor_list', 'Danh sách bác sĩ'), ('disease_prediction', 'Dự đoán bệnh'), ('disease_prediction_result', 'Kết quả dự đoán bệnh')], default='text', max_length=30),
        ),
    ]
